[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crosslift" 
version = "0.1.0"
dependencies = [
    "puzpy",
]

[tool.setuptools.packages.find]
where = ["src"] 


[project.scripts]
crosslift-create = "crosslift.create_puzzle:main"
crosslift-clues = "crosslift.make_clues:main"
crosslift-puz = "crosslift.save_puzzle:main"